# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

name: $(BuildVersion).$(Date:yyMMdd).$(Rev:r)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: (Get-Content .\tests\ElCamino.AspNetCore.Identity.AzureTable.Tests\config.json) | Foreach-Object { $_ -replace 'UseDevelopmentStorage=true;', '$(StorageConnection)'} | Set-Content .\tests\ElCamino.AspNetCore.Identity.AzureTable.Tests\config.json

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 6.x'
  inputs:
    version: 6.x

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 8.x'
  inputs:
    version: 8.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/ElCamino.AspNetCore.Identity.AzureTable.sln'
    arguments: '-c $(BuildConfiguration) -p:Version=$(BuildVersion)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    publishTestResults: true
    projects: '**/**.Tests.csproj'
    arguments: '--no-build --collect:"XPlat Code Coverage" -c $(BuildConfiguration) -v d'

- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage'
  inputs:
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- task: CopyFiles@1
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     **/*.dll
     **/*.nupkg
     **/*.snupkg
     **/*.zip
     **/publish/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'